// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tracyshandmadesoaps.soapstore.domain;

import com.tracyshandmadesoaps.soapstore.domain.ProductFulfillment;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductFulfillment_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ProductFulfillment.entityManager;
    
    public static final EntityManager ProductFulfillment.entityManager() {
        EntityManager em = new ProductFulfillment().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ProductFulfillment.countProductFulfillments() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProductFulfillment o", Long.class).getSingleResult();
    }
    
    public static List<ProductFulfillment> ProductFulfillment.findAllProductFulfillments() {
        return entityManager().createQuery("SELECT o FROM ProductFulfillment o", ProductFulfillment.class).getResultList();
    }
    
    public static ProductFulfillment ProductFulfillment.findProductFulfillment(Long id) {
        if (id == null) return null;
        return entityManager().find(ProductFulfillment.class, id);
    }
    
    public static List<ProductFulfillment> ProductFulfillment.findProductFulfillmentEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProductFulfillment o", ProductFulfillment.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ProductFulfillment.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ProductFulfillment.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ProductFulfillment attached = ProductFulfillment.findProductFulfillment(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ProductFulfillment.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ProductFulfillment.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ProductFulfillment ProductFulfillment.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProductFulfillment merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
