// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tracyshandmadesoaps.soapstore.domain;

import com.tracyshandmadesoaps.soapstore.domain.ProductFulfillment;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ProductFulfillment_Roo_Jpa_Entity {
    
    declare @type: ProductFulfillment: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ProductFulfillment.id;
    
    @Version
    @Column(name = "version")
    private Integer ProductFulfillment.version;
    
    public Long ProductFulfillment.getId() {
        return this.id;
    }
    
    public void ProductFulfillment.setId(Long id) {
        this.id = id;
    }
    
    public Integer ProductFulfillment.getVersion() {
        return this.version;
    }
    
    public void ProductFulfillment.setVersion(Integer version) {
        this.version = version;
    }
    
}
