// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tracyshandmadesoaps.soapstore.domain;

import com.tracyshandmadesoaps.soapstore.domain.Product;
import com.tracyshandmadesoaps.soapstore.domain.ProductFulfillment;

privileged aspect ProductFulfillment_Roo_JavaBean {
    
    public Product ProductFulfillment.getProduct() {
        return this.product;
    }
    
    public void ProductFulfillment.setProduct(Product product) {
        this.product = product;
    }
    
    public Integer ProductFulfillment.getQuantity() {
        return this.quantity;
    }
    
    public void ProductFulfillment.setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    
}
