// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tracyshandmadesoaps.soapstore.domain;

import com.tracyshandmadesoaps.soapstore.domain.ProductFulfillment;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect ProductFulfillment_Roo_Json {
    
    public String ProductFulfillment.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static ProductFulfillment ProductFulfillment.fromJsonToProductFulfillment(String json) {
        return new JSONDeserializer<ProductFulfillment>().use(null, ProductFulfillment.class).deserialize(json);
    }
    
    public static String ProductFulfillment.toJsonArray(Collection<ProductFulfillment> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<ProductFulfillment> ProductFulfillment.fromJsonArrayToProductFulfillments(String json) {
        return new JSONDeserializer<List<ProductFulfillment>>().use(null, ArrayList.class).use("values", ProductFulfillment.class).deserialize(json);
    }
    
}
